# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import xiao.help


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('picurl', models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/06'))),
                ('video', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('player_a', models.IntegerField(choices=[(33, '李四1'), (34, '张三'), (35, '王五')], default=0)),
                ('player_b', models.IntegerField(choices=[(33, '李四1'), (34, '张三'), (35, '王五')], default=0)),
            ],
            options={
                'verbose_name': '赛事对决',
                'verbose_name_plural': '赛事对决',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='姓名')),
                ('eng_name', models.CharField(default='', max_length=300, verbose_name='英文名')),
                ('height', models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(100)], verbose_name='身高cm')),
                ('age', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)], verbose_name='年龄')),
                ('level', models.CharField(choices=[('轻量级(70KG)', '轻量级(70KG)'), ('轻量级(80KG)', '轻量级(80KG)'), ('轻量级(90KG)', '轻量级(90KG)'), ('重量级(100KG)', '重量级(100KG)'), ('重量级(110KG)', '重量级(110KG)'), ('重量级(120KG)', '重量级(120KG)')], max_length=50, verbose_name='级别')),
                ('rule', models.CharField(choices=[('自由搏击', '自由搏击')], max_length=50, verbose_name='赛制')),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='国籍')),
                ('alias', models.CharField(blank=True, max_length=50, verbose_name='绰号')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='场馆')),
                ('history', models.CharField(blank=True, max_length=2000, verbose_name='历史战绩')),
                ('glory', models.CharField(blank=True, max_length=2000, verbose_name='头衔')),
                ('summary', models.TextField(blank=True, max_length=2001, verbose_name='简介')),
                ('picurl', models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/06'), verbose_name='照片')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '选手',
                'verbose_name_plural': '选手',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xiao.Title'),
        ),
    ]
