# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '赛事分类', 'verbose_name_plural': '赛事分类'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiao.Title', verbose_name='赛事分类'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=200, verbose_name='赛事分类'),
        ),
    ]
