# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0002_auto_20171206_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='game_date',
            field=models.DateTimeField(auto_now=True, verbose_name='比赛时间'),
        ),
    ]
