# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0004_auto_20171206_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/07')),
        ),
        migrations.AlterField(
            model_name='player',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/07'), verbose_name='照片'),
        ),
    ]
