# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0005_auto_20171207_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attr',
            field=models.CharField(choices=[('0', '--'), ('1', '首页')], default='0', max_length=2, verbose_name='自定义属性'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/08')),
        ),
        migrations.AlterField(
            model_name='player',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/08'), verbose_name='照片'),
        ),
    ]
