# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0006_auto_20171208_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attr',
            field=models.CharField(choices=[('0', ''), ('1', '首页')], default='', max_length=2, verbose_name='自定义属性'),
        ),
    ]
