# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0007_auto_20171208_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('picurl', models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/11'))),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '资讯',
                'verbose_name': '资讯',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/11')),
        ),
        migrations.AlterField(
            model_name='player',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/11'), verbose_name='照片'),
        ),
    ]
