# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0008_auto_20171211_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='writings',
            name='content',
            field=models.CharField(default='', max_length=10000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
        ),
    ]
