# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0009_auto_20171211_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writings',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='pub_date',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
