# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0011_auto_20171211_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.IntegerField(default=0, verbose_name='会员ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='aid',
            field=models.IntegerField(default=0, verbose_name='视频ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wid',
            field=models.IntegerField(default=0, verbose_name='文章ID'),
        ),
    ]
