# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0012_auto_20171211_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='writings',
            name='view',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
    ]
