# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0013_auto_20171211_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=200)),
                ('avatarUrl', models.CharField(default='', max_length=200, verbose_name='头像')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('country', models.CharField(default='', max_length=20, verbose_name='国家')),
                ('gender', models.IntegerField(default=0, max_length=1, verbose_name='姓别')),
                ('language', models.CharField(default='', max_length=20, verbose_name='语言')),
                ('nickName', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/13')),
        ),
        migrations.AlterField(
            model_name='player',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/13'), verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/13'), verbose_name=''),
        ),
    ]
