# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0015_auto_20171213_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatarUrl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/13'), verbose_name='头像'),
        ),
    ]
