# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0017_auto_20171213_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatarUrl',
            field=models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2017/12/13'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default=0, verbose_name='姓别'),
        ),
    ]
