# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0020_auto_20171213_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500, verbose_name='场馆名称')),
                ('picurl', models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2017/12/20'), verbose_name='场馆座位图')),
                ('address', models.CharField(default='', max_length=500, verbose_name='地址')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name_plural': '场馆',
                'verbose_name': '场馆',
            },
        ),
        migrations.CreateModel(
            name='Price_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField(default='0.00', verbose_name='原价')),
                ('price', models.FloatField(default='0.00', verbose_name='会员价')),
                ('color', models.CharField(default='', max_length=20, verbose_name='显示颜色')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiao.Title', verbose_name='场馆')),
            ],
            options={
                'verbose_name_plural': '票价',
                'verbose_name': '票价',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/20')),
        ),
        migrations.AlterField(
            model_name='player',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/20'), verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatarUrl',
            field=models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2017/12/20'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2017/12/20'), verbose_name=''),
        ),
    ]
