# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0021_auto_20171220_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_place',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiao.Place', verbose_name='场馆'),
        ),
    ]
