# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0022_auto_20171220_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '赛事对决', 'verbose_name_plural': '2.赛事对决'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '7.评论'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '场馆', 'verbose_name_plural': '3.场馆'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '选手', 'verbose_name_plural': '5.选手'},
        ),
        migrations.AlterModelOptions(
            name='price_place',
            options={'verbose_name': '票价', 'verbose_name_plural': '4.票价'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '赛事分类', 'verbose_name_plural': '1.赛事分类'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户', 'verbose_name_plural': '6.用户'},
        ),
        migrations.AlterModelOptions(
            name='writings',
            options={'verbose_name': '资讯', 'verbose_name_plural': '8.资讯'},
        ),
        migrations.AddField(
            model_name='article',
            name='pid',
            field=models.IntegerField(choices=[(3, 'funcit funk(付费直播) 福建 福州')], default=0, verbose_name='场馆'),
        ),
        migrations.AlterField(
            model_name='place',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='price_place',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
