# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0023_auto_20171220_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('pid', models.IntegerField(default=0, verbose_name='场馆ID')),
                ('price_id', models.IntegerField(default=0, verbose_name='票价ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('tel', models.CharField(default='', max_length=20, verbose_name='电话')),
                ('area', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '9.订单',
                'verbose_name': '订单',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='pid',
            field=models.IntegerField(choices=[(0, ''), (3, 'funcit funk(付费直播) 福建 福州')], default=0, verbose_name='场馆'),
        ),
    ]
