# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0024_auto_20171220_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
