# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0029_auto_20171221_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiao.Ordering', verbose_name='支付单号'),
        ),
    ]
