# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0031_auto_20171223_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='total_fee',
            field=models.FloatField(default='0.00', verbose_name='交易金额'),
        ),
    ]
