# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0038_auto_20171227_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='登陆次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='login_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后登陆时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('1', '轻量级(70KG)'), ('2', '轻量级(80KG)'), ('3', '轻量级(90KG)'), ('4', '重量级(100KG)'), ('5', '重量级(110KG)'), ('6', '重量级(120KG)')], max_length=50, verbose_name='级别'),
        ),
    ]
