# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0039_auto_20171227_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_count',
            field=models.IntegerField(default=1, verbose_name='登陆次数'),
        ),
    ]
