# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0041_auto_20171228_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='exercise_time',
            field=models.IntegerField(choices=[(0, '7天'), (1, '一个月'), (2, '三个月'), (3, '6个月'), (4, '8个月'), (5, '一年'), (6, '二年')], default=0, verbose_name='课程时间'),
        ),
    ]
