# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0042_auto_20171228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='teach_ids',
            field=models.ManyToManyField(to='xiao.Teach'),
        ),
    ]
