# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import xiao.help


class Migration(migrations.Migration):

    dependencies = [
        ('xiao', '0044_auto_20180105_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='writings',
            name='shorttitle',
            field=models.CharField(default='', max_length=200, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2018/01/09')),
        ),
        migrations.AlterField(
            model_name='lession',
            name='picurl',
            field=models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2018/01/09'), verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='place',
            name='picurl',
            field=models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2018/01/09'), verbose_name='场馆座位图'),
        ),
        migrations.AlterField(
            model_name='player',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2018/01/09'), verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='picurl',
            field=models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2018/01/09'), verbose_name='教练照片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatarUrl',
            field=models.ImageField(max_length=500, upload_to=xiao.help.PathAndRename('images/2018/01/09'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='picurl',
            field=models.ImageField(upload_to=xiao.help.PathAndRename('images/2018/01/09'), verbose_name=''),
        ),
    ]
