module.exports={
  appId:'wx79ea0abb620d7d72',
  secret:'1cd4389b51a0548bdedc7f783fd9441c',
  mch_id: '1493400272',
  merchant_key: '5582447b37dad5e6c3590afa0d5acf4a',
    page_size : 10,//默认每页显示调试
    api:{
        url:'https://django2.yy.lanrenmb.com',
        search:'https://xiao.lanrenmb.com/test_plus/search.php?kwtype=0&q=',
        index:'https://django2.yy.lanrenmb.com/xiao/index/',
        count:'https://xiao.lanrenmb.com/test_plus/lanren_count.php?type=',
        player:'https://django2.yy.lanrenmb.com/xiao/player/',
        player_list:'https://django2.yy.lanrenmb.com/xiao/player_list/',
        type_list:'https://django2.yy.lanrenmb.com/xiao/type_list/',
        lession_list:'https://django2.yy.lanrenmb.com/xiao/lession_list/',
        video_list:'https://django2.yy.lanrenmb.com/xiao/video_list/',
        comment_list:'https://django2.yy.lanrenmb.com/xiao/comment_list/',
        video:'https://django2.yy.lanrenmb.com/xiao/video/',
        content:'https://django2.yy.lanrenmb.com/xiao/content/',
        comment_post:'https://django2.yy.lanrenmb.com/xiao/comment_post/',
        userinfo:'https://django2.yy.lanrenmb.com/xiao/userinfo/',
        userinfo_post:'https://django2.yy.lanrenmb.com/xiao/userinfo_post/',
        ordering_post:'https://django2.yy.lanrenmb.com/xiao/ordering_post/',
        ordering_update:'https://django2.yy.lanrenmb.com/xiao/ordering_update/',
        area:'https://django2.yy.lanrenmb.com/xiao/area/',
        price:'https://django2.yy.lanrenmb.com/xiao/price/',
        wxpay:'https://django2.yy.lanrenmb.com/xiao/wxpay/',
        myOrder:'https://django2.yy.lanrenmb.com/xiao/myOrder/',
        app_choices:'https://django2.yy.lanrenmb.com/xiao/app_choices/',
        wxpay_notify:'https://django2.yy.lanrenmb.com/xiao/wxpay_notify/',
    }
}
